default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: giauvip
  host: localhost

development:
  <<: *default
  database: webruby_development

test:
  <<: *default
  database: webruby_test

production:
  <<: *default
  database: webruby_production
